version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: epiczone    
      MYSQL_USER: user_admin             
      MYSQL_PASSWORD: password123        
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql 
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend 
    ports:
      - "8080:80"  
    networks:
      - app-network

  backend:
    build:
      context: ./backend 
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/epiczone
      SPRING_DATASOURCE_USERNAME: user_admin
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
